# Generated by Django 5.2.7 on 2025-10-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text="The user's unique email address.", max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', help_text="The user's first name.", max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', help_text="The user's last name.", max_length=30, null=True)),
                ('registration_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Indicates whether the user has all admin permissions. Defaults to False.')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates whether the user account is active. Defaults to False and user needs to verify email on signup before it can be set to True.')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user joined.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
