# Generated by Django 5.2.7 on 2025-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user account is active. Defaults to False and user needs to verify email on signup before it can be set to True.'),
        ),
    ]
